version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  # Enable version updates for test dependencies
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "test-deps"
      include: "scope"
    labels:
      - "dependencies"
      - "testing"
      - "python"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
